### ISSUE TITLE
Button triggers events outside expected area

### ISSUE THREAD

**Issue by monolithed** [nerdyman/react-compare-slider#157] opened 2024-11-26 10:29 UTC
After disabling sliding on click, I found that the button not only occupies its space, but also the space above and below. In the default state, this doesn’t cause any issues, but when `onlyHandleDraggable` is set, it behaves like a bug because the event triggers where it’s not expected.

<img width="699" alt="Screenshot 2024-11-26 at 17 20 24" src="https://github.com/user-attachments/assets/f7b3a239-9a51-4bd0-8af2-459db5f5953f">

I'd also like to add that clicking on the button itself triggers the sliding, which causes an accidental flicker. The button area should be safe from sliding imho.

**Comment by nerdyman** [comment] 2024-11-26 18:34
Thanks @monolithed, that is intended behaviour although it may see a bit unintuitive. 

The `handle` is rendered within a container and it's the container that really handles the keyboard, pointer and aria attribute bindings. Otherwise the `handle` component would to handle this itself directly which would make it generally difficult to use / easy to break.

I could see some kind of zero width/height CSS approach working where the handle expands outside of the bounds of the container. Or possibly disabling pointer events on the container and enabling them on the `handle` component itself. However, I'd rather not have to enforce that all `handle` components set `pointer-events: auto` themselves or have to mess about with CSS selectors to target the immediate children of the container to reenable pointer events.

If you have any suggestions on how to allow the container to still handle the slider logic while only having the actual `handle` component clickable let me know.

**Comment by monolithed** [comment] 2024-11-27 07:05
> I'm not following this bit, are you saying that clicking on different places of the button also moves the slider position? If so that's intended, the position of the handle is based on where you click within the entire slider component.


@nerdyman, thanks for the workaround, it helped me solve the issue. About the second case — I’ve recorded a video where I click a button, and the slider moves toward the cursor. I believe this is a bug since the `onlyHandleDraggable` property implies sliding should work by dragging, not clicking.


https://github.com/user-attachments/assets/e8413340-e98c-4e41-8bb7-73cf0958117b

**Comment by nerdyman** [comment] 2024-11-27 12:25
Ah I see @monolithed, `onlyHandleDraggable` should probably be called `onlyHandleMoveable` or something to better reflect the behaviour but the way that it currently works in intentional.

**Comment by monolithed** [comment] 2024-11-27 13:26
@nerdyman thanks for helping me! I also noticed the workaround with pointer-events isn’t working with my custom handle component. I'll try to figure out why.

**Comment by monolithed** [comment] 2024-11-28 06:31
Figured it out. For the custom handle component, I needed to add `pointer-events: auto;`.

**Comment by nerdyman** [comment] 2024-11-28 11:51
It's the default behaviour of pretty much all comparison slider libraries from what I've seen.

If the additional behaviour were to be introduced, it would probably be better as a separate prop since it can apply to both the default dragging functionality and `onlyHandleDraggable`. 

Something like `interactionTrigger='pointerdown'|'pointermove'` would keep it separate from `onlyHandleDraggable` and support the existing behaviour too. `pointermove` would be the default and `pointerdown` would provide the functionality you're looking for.

It needs a bit more thought and should introducible as a non-breaking feature so won't be part of the initial v4 release. If you'd like it added in a future release feel free to open a separate ticket.

I'm going to close this ticket now since the main issue has been resolved.

**Closed by nerdyman** 2024-11-28 11:51 UTC
Labels: question, has workaround
