### ISSUE TITLE
bug: TypeError: Cannot read properties of null (Refs Issue)

### ISSUE THREAD

**Issue by brandon206** [nerdyman/react-compare-slider#62] opened 2022-01-19 02:07 UTC
**Bug: Both `clipContainerRef` and `handleContainerRef`'s `current` prop will output to `null`.**

If a user were to refresh the page, the default `null` value will be set. As a result, it will display this `TypeError` that I've screenshotted below. I've tried this using the `codepen` code [link](https://codesandbox.io/s/react-compare-slider-simple-example-9si6l).

![DwellWell](https://user-images.githubusercontent.com/41837945/150048996-efc21214-ba8f-496d-941e-5368b85b61eb.png)

**proposed solution:**
add the following conditionals to for the `refs` in `ReactCompareSlider.tsx`
```
if (clipContainerRef && clipContainerRef.current) {
  (clipContainerRef.current as HTMLElement).style.clip = _portrait
    ? `rect(auto,auto,${clampedPx}px,auto)`
    : `rect(auto,${clampedPx}px,auto,auto)`;
}
if (handleContainerRef && handleContainerRef.current) {
  (handleContainerRef.current as HTMLElement).style.transform = _portrait
    ? `translate3d(0,${clampedPx}px,0)`
    : `translate3d(${clampedPx}px,0,0)`;
}
```

**Comment by nerdyman** [comment] 2022-01-19 12:25
Hey @brandon206, thanks for opening the issue.

Can you provide steps to reproduce the error, including browser version and OS? The CodeSandbox works OK for me. 

AFAICT it *shouldn't* be possible for the refs to be `null` in `updateInternalPosition` as it either runs on a `useEffect` or by user driven events, by which time the refs will be registered.

**Comment by nerdyman** [comment] 2022-01-25 11:03
@brandon206 I'm going to close this for now as I can't reproduce it. Feel free to reopen the issue if you're able to repro it :)

**Closed by nerdyman** 2022-01-25 11:03 UTC
